version: '2'
services:

  cassandra:
    image: cassandra:3.11
    hostname: "sandbox"
    volumes:
      - ./data:/data
    ports:
      - "9160:9160"
      - "9042:9042"
  task: 
    image: guherbozdogan2/repo:latest
    depends_on: 
      - "cassandra"
    hostname: "sandbox"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx2g
    links:
      - cassandra
    volumes:
      - ./data:/data

